---
title: "Final Project"
author: "Emely Gazarov, Ryo Iwata, Maria Ramirez"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(knitr)
library(car)
# to control default number formatting, no need for specifying digits in kable.
options(scipen = 3, digits = 5) 
```

```{r}
all_addiction_data = read_rds("./addiction.rds")
```

```{r}
factored_addiction_data <- all_addiction_data |>
  # Demographics
  mutate(age = age_today.baseline) |>
  mutate(gender = as_factor(gender.baseline)) |>
  mutate(education = as_factor(ed_summary.baseline)) |>
  mutate(sobriety_calc = sobriety_calc.baseline) |>
  mutate(days_in_tx_clean = days_in_tx_clean.baseline) |>
  mutate(dropout_yn = as_factor(dropout_yn.baseline)) |>
  # SUD
  mutate(sa_dx_Alchohol = as_factor(sa_dx___0.baseline)) |>
  mutate(sa_dx_Opioid = as_factor(sa_dx___1.baseline)) |>
  mutate(sa_dx_Cannabis = as_factor(sa_dx___2.baseline)) |>
  mutate(sa_dx_sedative_hypnotic_anxiolytic = as_factor(sa_dx___3.baseline)) |>
  mutate(sa_dx_Cocaine = as_factor(sa_dx___4.baseline)) |>
  mutate(sa_dx_Other_stimulant = as_factor(sa_dx___5.baseline)) |>
  mutate(sa_dx_Hallucinogen = as_factor(sa_dx___6.baseline)) |>
  mutate(sa_dx_Nicotine = as_factor(sa_dx___7.baseline)) |>
  mutate(sa_dx_Inhalant = as_factor(sa_dx___8.baseline)) |>
  mutate(sa_dx_psychoactive = as_factor(sa_dx___9.baseline)) |>
  mutate(sa_dx_sum = sa_dx_sum.baseline) |>
  # Social support
  mutate(mspss_fam_sub_total = mspss_fam_sub_total.baseline) |>
  mutate(mspss_friends_sub_total = mspss_friends_sub_total.baseline) |>
  mutate(mspss_total = mspss_total.baseline) |>
  mutate(mspss_sig_other_sub_total = mspss_sig_other_sub_total.baseline) |>
  # Substance use history
  mutate(has_tried_tobacco = as_factor(newace18a___1.baseline)) |>
  mutate(has_tried_alcohol = as_factor(newace18a___2.baseline)) |>
  mutate(has_tried_other = as_factor(newace18a___10.baseline)) |>
  mutate(age_tried_tobacco = newace18b.baseline) |>
  mutate(age_tried_alcohol = newace18c.baseline) |>
  mutate(age_tried_other = newace18d.baseline) |>
  mutate(is_regular_tobacco = as_factor(newace19a___1.baseline)) |>
  mutate(is_regular_alcohol = as_factor(newace19b.baseline)) |>
  mutate(is_regular_other = as_factor(newace19c.baseline)) |>
  mutate(age_regular_tobacco = newace19b.baseline) |>
  mutate(age_regular_alcohol = newace19c.baseline) |>
  mutate(age_regular_other = newace19d.baseline) |>
  # AA/NA Affiliation
  # Lifetime meetings calculation	if([aaas_8]=0, 0,if([aaas_8]>0 and [aaas_8]<=30, 0.25, if([aaas_8]>=31 and [aaas_8]<=90,0.50, if([aaas_8]>90 and [aaas_8]<=500, 0.75, if([aaas_8]>=501,1,0)))))
  mutate(aaas_calc_lifetime = aaas_calc_lifetime.baseline) |>
 # Past year meetings calculation	if([aaas_9]=0,0,if([aaas_9]>0 and [aaas_9]<=65, 0.25, if([aaas_9]>=66 and [aaas_9]<=130, 0.50, if([aaas_9]>130 and [aaas_9]<=195, 0.75, if([aaas_9]>=196,1,0)))))
  mutate(aaas_calc_past_year = aaas_calc_past_year.baseline) |>
# Total AAAS Score	sum([aaas_1],[aaas_2],[aaas_3],[aaas_4],[aaas_5],[aaas_6],[aaas_7],[aaas_calc_lifetime],[aaas_calc_past_year])
  mutate(aaas_total = aaas_total.baseline) |>
  mutate(tspe_positive = tspe_positive.baseline) |>
  mutate(tspe_negative = tspe_negative.baseline) |>

  # Stressful life events
  # 1. Natural disaster	1, Happened to you | 2, Witnessed it happen | 3, Learned about it happening | 4, Exposed as part of job | 5, Not sure | 6, Doesn't apply
  mutate(natural_disaster.happened_to_you = as_factor(lec_2_1___1.baseline)) |>
  mutate(natural_disaster.witnessed = as_factor(lec_2_1___2.baseline)) |>
  mutate(natural_disaster.learned = as_factor(lec_2_1___3.baseline)) |>
  mutate(natural_disaster.exposed = as_factor(lec_2_1___4.baseline)) |>
  # 2. Fire or explosion
  mutate(fire.happened_to_you = as_factor(lec_2_2___1.baseline)) |>
  mutate(fire.witnessed = as_factor(lec_2_2___2.baseline)) |>
  mutate(fire.learned = as_factor(lec_2_2___3.baseline)) |>
  mutate(fire.exposed = as_factor(lec_2_2___4.baseline)) |>
  # 3. Transportation accident
  mutate(transportation_accident.happened_to_you = as_factor(lec_2_3___1.baseline)) |>
  mutate(transportation_accident.witnessed = as_factor(lec_2_3___2.baseline)) |>
  mutate(transportation_accident.learned = as_factor(lec_2_3___3.baseline)) |>
  mutate(transportation_accident.exposed = as_factor(lec_2_3___4.baseline)) |>
  # 4. Serious accident
  mutate(serious_accident.happened_to_you = as_factor(lec_2_4___1.baseline)) |>
  mutate(serious_accident.witnessed = as_factor(lec_2_4___2.baseline)) |>
  mutate(serious_accident.learned = as_factor(lec_2_4___3.baseline)) |>
  mutate(serious_accident.exposed = as_factor(lec_2_4___4.baseline)) |>
  # 5. Toxic substance
  mutate(toxic.happened_to_you = as_factor(lec_2_5___1.baseline)) |>
  mutate(toxic.witnessed = as_factor(lec_2_5___2.baseline)) |>
  mutate(toxic.learned = as_factor(lec_2_5___3.baseline)) |>
  mutate(toxic.exposed = as_factor(lec_2_5___4.baseline)) |>
  # 6. Physical assault
  mutate(physical_assault.happened_to_you = as_factor(lec_2_6___1.baseline)) |>
  mutate(physical_assault.witnessed = as_factor(lec_2_6___2.baseline)) |>
  mutate(physical_assault.learned = as_factor(lec_2_6___3.baseline)) |>
  mutate(physical_assault.exposed = as_factor(lec_2_6___4.baseline)) |>
  # 7. Assault with weapon
  mutate(weapon_assault.happened_to_you = as_factor(lec_2_7___1.baseline)) |>
  mutate(weapon_assault.witnessed = as_factor(lec_2_7___2.baseline)) |>
  mutate(weapon_assault.learned = as_factor(lec_2_7___3.baseline)) |>
  mutate(weapon_assault.exposed = as_factor(lec_2_7___4.baseline)) |>
  # 8. Sexual assault
  mutate(sexual_assault.happened_to_you = as_factor(lec_2_8___1.baseline)) |>
  mutate(sexual_assault.witnessed = as_factor(lec_2_8___2.baseline)) |>
  mutate(sexual_assault.learned = as_factor(lec_2_8___3.baseline)) |>
  mutate(sexual_assault.exposed = as_factor(lec_2_8___4.baseline)) |>
  # 9. Unwanted sexual experience
  mutate(unwanted_sexual.happened_to_you = as_factor(lec_2_9___1.baseline)) |>
  mutate(unwanted_sexual.witnessed = as_factor(lec_2_9___2.baseline)) |>
  mutate(unwanted_sexual.learned = as_factor(lec_2_9___3.baseline)) |>
  mutate(unwanted_sexual.exposed = as_factor(lec_2_9___4.baseline)) |>
  # 10. Combat or war exposure
  mutate(combat.happened_to_you = as_factor(lec_2_10___1.baseline)) |>
  mutate(combat.witnessed = as_factor(lec_2_10___2.baseline)) |>
  mutate(combat.learned = as_factor(lec_2_10___3.baseline)) |>
  mutate(combat.exposed = as_factor(lec_2_10___4.baseline)) |>
  # 11. Captivity
  mutate(captivity.happened_to_you = as_factor(lec_2_11___1.baseline)) |>
  mutate(captivity.witnessed = as_factor(lec_2_11___2.baseline)) |>
  mutate(captivity.learned = as_factor(lec_2_11___3.baseline)) |>
  mutate(captivity.exposed = as_factor(lec_2_11___4.baseline)) |>
  # 12. Life-threatening illness
  mutate(illness.happened_to_you = as_factor(lec_2_12___1.baseline)) |>
  mutate(illness.witnessed = as_factor(lec_2_12___2.baseline)) |>
  mutate(illness.learned = as_factor(lec_2_12___3.baseline)) |>
  mutate(illness.exposed = as_factor(lec_2_12___4.baseline)) |>
  # 13. Severe human suffering
  mutate(severe_suffering.happened_to_you = as_factor(lec_2_13___1.baseline)) |>
  mutate(severe_suffering.witnessed = as_factor(lec_2_13___2.baseline)) |>
  mutate(severe_suffering.learned = as_factor(lec_2_13___3.baseline)) |>
  mutate(severe_suffering.exposed = as_factor(lec_2_13___4.baseline)) |>
  # 14. Sudden violent death
  mutate(sudden_violent_death.happened_to_you = as_factor(lec_2_14___1.baseline)) |>
  mutate(sudden_violent_death.witnessed = as_factor(lec_2_14___2.baseline)) |>
  mutate(sudden_violent_death.learned = as_factor(lec_2_14___3.baseline)) |>
  mutate(sudden_violent_death.exposed = as_factor(lec_2_14___4.baseline)) |>
  # 15. Sudden accidental death
  mutate(sudden_accidental_death.happened_to_you = as_factor(lec_2_15___1.baseline)) |>
  mutate(sudden_accidental_death.witnessed = as_factor(lec_2_15___2.baseline)) |>
  mutate(sudden_accidental_death.learned = as_factor(lec_2_15___3.baseline)) |>
  mutate(sudden_accidental_death.exposed = as_factor(lec_2_15___4.baseline)) |>
  # 16. Serious injury or harm caused to someone else
  mutate(harm_to_others.happened_to_you = as_factor(lec_2_16___1.baseline)) |>
  mutate(harm_to_others.witnessed = as_factor(lec_2_16___2.baseline)) |>
  mutate(harm_to_others.learned = as_factor(lec_2_16___3.baseline)) |>
  mutate(harm_to_others.exposed = as_factor(lec_2_16___4.baseline)) |>
  # 17. Any other very stressful experience
  mutate(other_stressful.happened_to_you = as_factor(lec_2_17___1.baseline)) |>
  mutate(other_stressful.witnessed = as_factor(lec_2_17___2.baseline)) |>
  mutate(other_stressful.learned = as_factor(lec_2_17___3.baseline)) |>
  mutate(other_stressful.exposed = as_factor(lec_2_17___4.baseline)) |>
  # Total stress
  mutate(stressful_life.happened_to_you = toyou_total.baseline) |>
  mutate(stressful_life.happened_to_you_and_witnessed = toyou_wit_total.baseline) |>
  mutate(stressful_life.witnessed = witnessed_total.baseline) |>

  # Childhood
  #   "1. Did a parent or other adult in the household often or very often... 
  # 
  # Swear at you, insult you, put you down, or humiliate you?   
  # 
  #           OR
  # 
  # Act in a way that made you afraid that you might be physically hurt?"
  mutate(childhood.verbal_abuse = as_factor(ace1.baseline)) |>
  # "2. Did a parent or other adult in the household often or very often... 
  # 
  # Push, grab, slap, or throw something at you?
  # 
  #            OR    
  # 
  # Ever hit you so hard that you had marks or were injured?"
  mutate(childhood.physical_abuse = as_factor(ace2.baseline)) |>
  # "3. Did an adult or person at least 5 years older than you ever...
  # 
  # Touch or fondle you or have you touch their body in a sexual way?
  # 
  #            OR    
  # 
  # Attempt or actually have oral, anal, or vaginal intercourse with you?"
  mutate(childhood.sexual_abuse = as_factor(ace3.baseline)) |>
  # "4. Did you often or very often feel that ...
  # 
  # No one in your family loved you or thought you were important or special?
  # 
  #            OR    
  # 
  # Your family didn't look out for each other, feel close to each other, or support each other?"
  mutate(childhood.alone = as_factor(ace4.baseline)) |>
  # "5. Did you often or very often feel that ...
  # 
  # You didn't have enough to eat, had to wear dirty clothes, and had no one to protect you?
  # 
  #            OR    
  # 
  # Your parents were too drunk or high to take care of you or take you to the doctor if you needed it?"
  mutate(childhood.neglected = as_factor(ace5.baseline)) |>
  # 6. Were your parents ever separated or divorced?
  mutate(childhood.divorced = as_factor(ace2.baseline)) |>
  # "7. Was your mother or stepmother (or father/stepfather):
  # 
  # Often or very often pushed, grabbed, slapped, or had something thrown at her/him?
  # 
  #            OR    
  # 
  # Sometimes, often, or very often kicked, bitten, hit with a fist, or hit with something hard?
  # 
  #            OR    
  # 
  # Ever repeatedly hit at least a few minutes or threatened with a gun or knife?"
  mutate(childhood.parent_was_abused = as_factor(ace7.baseline)) |>
  # 7a. For Q7, indicate which parent was violated 
  # 8. Did you live with anyone who was a problem drinker or alcoholic or who used street drugs?
  mutate(childhood.other_was_addicted = as_factor(ace8.baseline)) |>
  # 9. Was a household member depressed or mentally ill, or did a household member attempt suicide?
  mutate(childhood.other_was_stressed = as_factor(ace9.baseline)) |>
  # 10. Did a household member go to prison?
  mutate(childhood.other_was_prisoned = as_factor(ace10.baseline)) |>
  # Total childhood
  mutate(total_ace_score = total_ace_score.baseline) |>

  # Spirituality and religion
  # 0, Atheist | 1, Agnostic | 2, Protestant | 3, Catholic | 4, Muslim | 5, Jewish | 6, Hindu | 7, Buddhist | 8, Baptist | 9, No religious affiliation | 10, Non-denominational Christian | 15, Other
  mutate(religion.Atheist = as_factor(brc_rel___0.baseline)) |>
  mutate(religion.Agnostic = as_factor(brc_rel___1.baseline)) |>
  mutate(religion.Protestant = as_factor(brc_rel___2.baseline)) |>
  mutate(religion.Catholic = as_factor(brc_rel___3.baseline)) |>
  mutate(religion.Muslim = as_factor(brc_rel___4.baseline)) |>
  mutate(religion.Jewish = as_factor(brc_rel___5.baseline)) |>
  mutate(religion.Hindu = as_factor(brc_rel___6.baseline)) |>
  mutate(religion.Buddhist = as_factor(brc_rel___7.baseline)) |>
  mutate(religion.Baptist = as_factor(brc_rel___8.baseline)) |>
  mutate(religion.No_affiliation = as_factor(brc_rel___9.baseline)) |>
  mutate(religion.Non_denominational_Christian = as_factor(brc_rel___10.baseline)) |>
  mutate(religion.Other = as_factor(brc_rel___15.baseline)) |>
  mutate(positive_spiritual_cope = as_factor(pos_cope.baseline)) |>
  mutate(negative_spiritual_cope = as_factor(neg_cope.baseline)) |>

  
  select(-contains(".baseline")) |>
  select(-contains(".discharge")) |>
  select(-contains(".followup")) |>
  select(-contains(".x.x")) |>
  select(-contains(".y.y"))




```


```{r}
drop_na(all_addiction_data, dropout_yn.baseline)
```

```{r}

```