---
title: "Final Project"
author: "Emely Gazarov, Ryo Iwata, Maria Ramirez"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidymodels)
library(knitr)
library(car)
# to control default number formatting, no need for specifying digits in kable.
options(scipen = 3, digits = 5) 
```

# Problem 1

## 1.A Load data and prepare data for analysis 

```{r loading in data}
# Reading in the data

# Predictor
## Basic demographics (age, gender, education) 
## Duration of sobriety prior to treatment
raw_demographics <- read_delim("./data/demo.damon.csv", delim = ",")
## Specific SUDs (e.g., alcohol use disorder)
raw_SUD <- read_delim("./data/SUDdiagnosis.damon.csv", delim = ",")
## Social Support (MSPSS)
raw_social_support <- read_delim("./data/mspss.damon.csv", delim = ",")
## Substance Use History
raw_sub_history <- read_delim("./data/subuse.damon.csv", delim = ",")
## AA/NA Affiliation 
raw_aana_affiliation <- read_delim("./data/aana.damon.csv", delim = ",")
## Stressful Life Experiences (LEC-5) lec.damon
"
*The structure of this dataframe is really bonkers. You probably want to use the variable “toyou_total” which is a sum of event types that the patients endorsed as having happened to them. We sometimes also use “toyou_wit_total”, which is a similar sum score, but includes events that have happened to the participant AND events that the participant has witnessed.
"
raw_stressful_life  <- read_delim("./data/lec.damon.csv", delim = ",")
## Spiritual Experiences (Brief R-COPE)
raw_spiritual <- read_delim("./data/r_cope.damon.csv", delim = ",")

# Things to predict
## Quality of Life (WHOQOL-BREF): Evaluates general, physical, psychological health, social relationships, and environment.
raw_life_quality <- read_delim("./data/QOL.damon.csv", delim = ",")
## raw_life_quality <- read_delim("./data/QOL.damon.csv", delim = ",")
raw_commitment <- read_delim("./data/change.damon.csv", delim = ",")
## Alcohol/Drug Craving (PACS): Measures the frequency and intensity of cravings.
raw_craving <- read_delim("./data/craving.damon.csv", delim = ",")
## Treatment dropout
## demo.damon (dropout_yn)
## Length of stay in treatment
## demo.damon (days_in_tx_clean)
## Impression of Change (PGIC)
raw_change_impression <- read_delim("./data/pgic.damon.csv", delim = ",")

# Other
raw_data_dictionary <- read_delim("./data/Data Dictionary.csv", delim = ",")
# Demographics

# Missing
## Childhood Experiences (ACE)
## aces.damon is missing

```


```{}
str(raw_demographics)
str(raw_SUD)
str(raw_social_support)
str(raw_sub_history)
str(raw_aana_affiliation)
str(raw_stressful_life)
str(raw_spiritual)
str(raw_life_quality)
str(raw_commitment)
str(raw_craving)
str(raw_change_impression)
str(raw_data_dictionary)
```

```{r}
# Filtering out readmission
raw_demographics |> filter(!str_detect(redcap_event_name,'readmission'))

# Filtering for subjects that are in each time

discharged_demo <- raw_demographics |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_demo <- raw_demographics |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_demo <- raw_demographics |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

```
```{r}
joined_demographics <- baseline_demo |> 
  inner_join(discharged_demo, by="record_id") |>
  inner_join(followup_demo, by="record_id")

```

# Getting baseline, followup, discharge for all datasets

```{r SUD}
# Filtering for subjects that are in each time

discharged_SUD <- raw_SUD |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_SUD <- raw_SUD |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_SUD <- raw_SUD |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_SUD <- baseline_SUD |> 
  inner_join(discharged_SUD, by="record_id") |>
  inner_join(followup_SUD, by="record_id")

```

```{r social support}
# Filtering for subjects that are in each time

discharged_social_support <- raw_social_support |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_social_support <- raw_social_support |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_social_support <- raw_social_support |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_social_support <- baseline_social_support |> 
  inner_join(discharged_social_support, by="record_id") |>
  inner_join(followup_social_support, by="record_id")
```

```{r substance history}
# Filtering for subjects that are in each time

discharged_sub_history <- raw_sub_history |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_sub_history <- raw_sub_history |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_sub_history <- raw_sub_history |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_sub_history <- baseline_sub_history |> 
  inner_join(discharged_sub_history, by="record_id") |>
  inner_join(followup_sub_history, by="record_id")
```

```{r aana affiliation}
# Filtering for subjects that are in each time

discharged_aana_affiliation <- raw_aana_affiliation |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_aana_affiliation <- raw_aana_affiliation |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_aana_affiliation <- raw_aana_affiliation |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_aana_affiliation <- baseline_aana_affiliation |> 
  inner_join(discharged_aana_affiliation, by="record_id") |>
  inner_join(followup_aana_affiliation, by="record_id")
```

```{r stressful life}
# Filtering for subjects that are in each time

discharged_stressful_life <- raw_stressful_life |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_stressful_life <- raw_stressful_life |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_stressful_life <- raw_stressful_life |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_stressful_life <- baseline_stressful_life |> 
  inner_join(discharged_stressful_life, by="record_id") |>
  inner_join(followup_stressful_life, by="record_id")
```

```{r spirituality}
# Filtering for subjects that are in each time

discharged_spiritual <- raw_spiritual |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_spiritual <- raw_spiritual |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_spiritual <- raw_spiritual |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_spiritual <- baseline_spiritual |> 
  inner_join(discharged_spiritual, by="record_id") |>
  inner_join(followup_spiritual, by="record_id")
```

```{r}
# Filtering for subjects that are in each time

discharged_life_quality <- raw_life_quality |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_life_quality <- raw_life_quality |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_life_quality <- raw_life_quality |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_life_quality <- baseline_life_quality |> 
  inner_join(discharged_life_quality, by="record_id") |>
  inner_join(followup_life_quality, by="record_id")
```

```{r craving}
# Filtering for subjects that are in each time

discharged_craving <- raw_craving |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_craving <- raw_craving |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_craving <- raw_craving |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_craving <- baseline_craving |> 
  inner_join(discharged_craving, by="record_id") |>
  inner_join(followup_craving, by="record_id")
```

```{r change impression}
# Filtering for subjects that are in each time

discharged_change_impression <- raw_change_impression |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_change_impression <- raw_change_impression |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_change_impression <- raw_change_impression |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_change_impression <- baseline_change_impression |> 
  inner_join(discharged_change_impression, by="record_id") |>
  inner_join(followup_change_impression, by="record_id")
```

```{r}
# Filtering for subjects that are in each time

discharged_commitment <- raw_commitment |>
  filter(str_detect(redcap_event_name,'discharge')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".discharge")))

baseline_commitment <- raw_commitment |>
  filter(str_detect(redcap_event_name,'baseline')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".baseline")))

followup_commitment <- raw_commitment |>
  filter(str_detect(redcap_event_name,'followup')) |>
  rename_with(~ ifelse(.x == "record_id", .x, paste0(.x, ".followup")))

joined_commitment <- baseline_commitment |> 
  inner_join(discharged_commitment, by="record_id") |>
  inner_join(followup_commitment, by="record_id")
```

# Joining all 

```{r}
all_addiction_data <- inner_join(joined_demographics, joined_aana_affiliation, by="record_id") |>
  inner_join(joined_change_impression, by="record_id") |>
  inner_join(joined_commitment, by="record_id") |>
  inner_join(joined_craving, by="record_id") |>
  inner_join(joined_life_quality, by="record_id") |>
  inner_join(joined_social_support, by="record_id") |>
  inner_join(joined_spiritual, by="record_id") |>
  inner_join(joined_stressful_life, by="record_id") |>
  inner_join(joined_sub_history, by="record_id") |>
  inner_join(joined_SUD, by="record_id")
```

```{r Craving EDA}
all_addiction_data |>
  ggplot(aes(pacs_mean.baseline, pacs_mean.discharge)) +
  geom_jitter()

all_addiction_data |>
  ggplot(aes(pacs_mean.baseline, pacs_mean.followup)) +
  geom_jitter()
```
```{r Craving EDA}
all_addiction_data |>
  ggplot() +
  geom_histogram(aes(pacs_mean.baseline))

all_addiction_data |>
  ggplot() +
  geom_histogram(aes(pacs_mean.followup))

all_addiction_data |>
  ggplot() +
  geom_histogram(aes(pacs_mean.discharge))

```
```{r EDA social support}
all_addiction_data |>
  ggplot(aes(mspss_fam_sub_total.baseline)) +
  geom_histogram()

all_addiction_data |>
  ggplot(aes(mspss_friends_sub_total.baseline)) +
  geom_histogram()

all_addiction_data |>
  ggplot(aes(mspss_sig_other_sub_total.baseline)) +
  geom_histogram()

all_addiction_data |>
  ggplot(aes(mspss_total.baseline)) +
  geom_histogram()
```

```{r AA NA thoughts}
all_addiction_data |>
  ggplot(aes(tspe_negative.baseline)) +
  geom_histogram()

all_addiction_data |>
  ggplot(aes(tspe_positive.baseline)) +
  geom_histogram()

```

```{r stressful life experiences}
all_addiction_data |>
  ggplot(aes(lec)) +
  geom_histogram()

all_addiction_data |>
  ggplot(aes(tspe_positive.baseline)) +
  geom_histogram()

```
